# Generated by Django 5.0 on 2023-12-11 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('rating', models.CharField(max_length=10)),
                ('comment_head', models.TextField()),
                ('comment', models.TextField()),
            ],
        ),
    ]
